// src/pages/index.ts
export { default as HomePage } from './HomePage'
export { default as AboutPage } from './AboutPage'
export { default as ProductPage } from './products/ProductPage'
export { default as CRUDPage } from './CRUDPage'
export { default as CuentaPage } from './CuentaPage'
export { default as NotFoundPage } from './NotFoundPage'
export { default as NavbarComponent } from './base/NavbarComponent'
export { default as FooterComponent } from './base/FooterComponent'
export { default as LoginPage } from './auth/LoginPage'
export { default as RegistroPage } from './auth/RegistroPage'
